project:
  type: website
  


website:
  title: "RainbowR"
  favicon: rainbowR-square.png
  twitter-card: true
  open-graph: true
  site-url: "https://rainbowr.netlify.app"
  
  navbar:
    #logo: rainbowR-square.png
    right:
      - text: "BLOG"
        file: blog.qmd
      - text: "JOIN"
        href: https://docs.google.com/forms/d/1y7SOWE3IW-fpR_5Cd4mK-CMUpFZ-hvhY4cTj34JqTVE/
      - text: "CODE OF CONDUCT"
        file: CoC.qmd
      - icon: github
        href: https://github.com/r-lgbtq
      - icon: twitter
        href: https://twitter.com/R_LGBTQ
        
format:
  html:
    theme: vapor # solar, morph
    css: styles.css
    include-after-body: fontawesome.html

editor: visual

# https://quarto.org/docs/websites/website-blog.html#themes
