project:
  type: website
  resources:
    "_redirects"

execute:
  freeze: true

website:
  title: "rainbowR"
  image: images/rainbowR-hex.png
  # image-alt: |
  #   A hexagon comprised of six diagonal stripes, in rainbow coulours, with a white horizonal stripe accross the centre containing the word rainbowR.
  favicon: images/rainbow-hex.png
  open-graph: true
  site-url: "https://rainbowr.netlify.app"
  
  navbar:
   # logo: rainbowR-square.svg
    right:
      - text: "Posts"
        file: posts.qmd
      - text: "Join"
        href: https://docs.google.com/forms/d/1y7SOWE3IW-fpR_5Cd4mK-CMUpFZ-hvhY4cTj34JqTVE/
      - text: "Meetups"
        href: meetups.qmd
      - text: "Code of Conduct"
        file: CoC.qmd
      - icon: github
        href: https://github.com/r-lgbtq
      - icon: mastodon
        href: https://tech.lgbt/@rainbowR
      
        
format:
  html:
    theme: 
      light: [cosmo, custom_light.scss]
      dark: [vapor, custom_dark.scss]
    css: styles.css

editor: source

# https://quarto.org/docs/websites/website-blog.html#themes
